apiVersion: v1
kind: Secret
metadata:
  name: gha-runner-secret
  namespace: actions-runner-system
stringData:
  github_app_id: "REPLACE_WITH_APP_ID"
  github_app_installation_id: "REPLACE_WITH_INSTALLATION_ID"
  github_app_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    REPLACE_WITH_PRIVATE_KEY
    -----END RSA PRIVATE KEY-----
