apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-runner-ai-staging
  namespace: actions-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gha-runner-ai-staging
  namespace: project-example-ai-staging
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-runner-ai-staging
  namespace: project-example-ai-staging
subjects:
  - kind: ServiceAccount
    name: gha-runner-ai-staging
    namespace: actions-runner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gha-runner-ai-staging
