apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-runner-ai
  namespace: actions-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gha-runner-ai
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
